/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AktiveFolkeavstemninger: typeof import('./src/components/AktiveFolkeavstemninger.vue')['default']
    Alert: typeof import('./src/components/Alert.vue')['default']
    AuthStatusChecker: typeof import('./src/components/AuthStatusChecker.vue')['default']
    AvgittStemmeDialog: typeof import('./src/components/app/dialogs/AvgittStemmeDialog.vue')['default']
    BekreftStemmeDialog: typeof import('./src/components/app/dialogs/BekreftStemmeDialog.vue')['default']
    Container: typeof import('./src/components/Container.vue')['default']
    Driftsmeldinger: typeof import('./src/components/Driftsmeldinger.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    InaktivAdvarselDialog: typeof import('./src/components/app/dialogs/InaktivAdvarselDialog.vue')['default']
    KunneIkkeAvleggeStemmeDialog: typeof import('./src/components/app/dialogs/KunneIkkeAvleggeStemmeDialog.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    LoggetUtDialog: typeof import('./src/components/app/dialogs/LoggetUtDialog.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ReadMore: typeof import('./src/components/ReadMore.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Spinner: typeof import('./src/components/Spinner.vue')['default']
    StyledButton: typeof import('./src/components/StyledButton.vue')['default']
    StyledLink: typeof import('./src/components/StyledLink.vue')['default']
  }
}
