// <auto-generated />
using System;
using Folkeavstemning.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Folkeavstemning.Api.Migrations
{
    [DbContext(typeof(FolkeavstemningContext))]
    [Migration("20231026135206_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Folkeavstemning.Api.Database.Stemmegivning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FolkeavstemningId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("folkeavstemning_id");

                    b.Property<string>("Manntallsnummer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("manntallsnummer");

                    b.HasKey("Id")
                        .HasName("pk_stemmegivninger");

                    b.ToTable("stemmegivninger", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
